### ISSUE TITLE
[q] HOW TO SOLVE THIS ERROR?

### ISSUE THREAD

**Issue by DazzlingCVa** [aaassseee/screen_brightness#10]
### Description (What are you difficulties)
E/flutter (18328): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setScreenBrightness on channel github.com/aaassseee/screen_brightness)

**Comment by aaassseee** [comment]
@DazzlingCVa What version and platform are you using?

**Comment by DazzlingCVa** [comment]
Android&IOS platform version 12 and above

**Comment by DazzlingCVa** [comment]
E/flutter (23989): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setScreenBrightness on channel github.com/aaassseee/screen_brightness) igot this Error

**Comment by aaassseee** [comment]
@DazzlingCVa  Are you using the latest version of library?

**Comment by DazzlingCVa** [comment]
yes

**Comment by aaassseee** [comment]
@DazzlingCVa I am not having you issue, I think your cached library make this error. Try pub upgrade or pub cache clean

**Comment by DazzlingCVa** [comment]
okay i will check

**Comment by haizadvnet** [comment]
I got this error when I installed the plugin during debug process. After I run `flutter clean` and `flutter pub get` command, and then  re-debug the apps, the error is gone.

**Comment by aaassseee** [comment]
@haizadvnet After install a native platform plugin, you must reinstall you app due to native code is missing hot reload or hot restart function. Hot reload and hot restart function only works with dart code.
