### ISSUE TITLE
[bug] Failed to support Flutter 3.3.4, Can not compile normally

### ISSUE THREAD

**Issue by chkecopy** [aaassseee/screen_brightness#13]
### Step to reproduce (how to reproduce the bug)
1.

**Comment by aaassseee** [comment]
Hi @chkecopy Can you provide any information? I am using the latest Flutter and works fine to me.

**Comment by aaassseee** [comment]
Hi @chkecopy. Any update?

**Comment by jack84156** [comment]
this plugin is work fine with me with `3.3.4` , very smart plugin

**Comment by aaassseee** [comment]
Close due to no response
