### ISSUE TITLE
[bug][Windows] Invalid pointer read fail fast unexpected heap exception

### ISSUE THREAD

**Issue by JulienDev** [aaassseee/screen_brightness#15]
### Description (bug summary)
I'm seeing a lot of crashes reported by Microsoft dev console. The name of the error is the following:
`invalid_pointer_read_fail_fast_unexpected_heap_exception_c0000409_screen_brightness_windows_plugin.dll!unknown`
Here is the stack trace they are providing :
[Apps-and-Games-Health-details-Stack-prevalance-Stack-Trace (1).csv](https://github.com/aaassseee/screen_brightness/files/10720584/Apps-and-Games-Health-details-Stack-prevalance-Stack-Trace.1.csv)

### Step to reproduce (how to reproduce the bug)
Honestly, I don't know what the users are doing to get the error.

### Platform (Android/iOS/macOS/Windows)
Windows

**Comment by aaassseee** [comment]
Hi, @JulienDev Thanks for the bug report. It needs time to find out what happened. If you have any updated information please feel free to leave a comment.

**Comment by aaassseee** [comment]
Hi, @JulienDev Did you test your app without any problem during normal usage?

**Comment by JulienDev** [comment]
On my computer, there is no crash when I'm using the app, but I have to say that the plugin is not working, I'm not able to get the current brightness or set the brightness. I'm using Windows 11 Pro

> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-1, Unable to change screen brightness., true, null)
> #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
> #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
> <asynchronous suspension>
> #2      MethodChannelScreenBrightness.setScreenBrightness (package:screen_brightness_platform_interface/method_channel_screen_brightness.dart:103:5)
> <asynchronous suspension>

**Comment by aaassseee** [comment]
If you cannot get or set brightness, that means your monitor didn't support [DCC/CI](https://en.wikipedia.org/wiki/Display_Data_Channel#DDC/CI). Can you find out is your monitor support DCC/CI?

**Comment by JulienDev** [comment]
Honestly I don't know, I'm using a laptop. BTW I think both issues are not related :)

**Comment by aaassseee** [comment]
Hi @JulienDev. I finally have time to check this issue. Are you still facing any error? Or  any new updates?
