### ISSUE TITLE
[q] change screen brightness in background

### ISSUE THREAD

**Issue by cagridurmus** [aaassseee/screen_brightness#17]
When I want to change the screen brightness while in the background, it doesn't change.(IOS)

**Comment by aaassseee** [comment]
Hi @cagridurmus, would you like to express more about changing brightness in background. As the os restriction on iOS. When user quit the app, brightness would reset back to system brightness. Which means as app developer you cannot change the system brightness, you can only change brightness when user is using the app.

**Comment by cagridurmus** [comment]
You added the setAutoReset method for the package. When I change the screen brightness in my own application and then go to the main screen, the screen brightness value stops. What I want to do is I want to change the system brightness while it is in the background. But as far as I understand, such a thing cannot be done on the iOS side.

**Comment by aaassseee** [comment]
Yes, that what I meant. You cannot change system brightness in iOS side, only application brightness is allowed.

**Comment by aaassseee** [comment]
@cagridurmus Is there any other question? If not feel free to close this issue.

**Comment by cagridurmus** [comment]
No, thanks bro.
