### ISSUE TITLE
[bug] Xcode compile error

### ISSUE THREAD

**Issue by zhuwei** [aaassseee/screen_brightness#18]
### Description (bug summary)
(lldb) dyld[14557]: Library not loaded: @rpath/libswiftCore.dylib

### Step to reproduce (how to reproduce the bug)
1. pubspec.yaml add screen_brightness: ^0.2.2
2. project run to device (I haven't written the code yet)
3. add the “usr/lib/swift” path to the Runpath Search Paths. Under debugging, the problem can be solved, but ad hoc or flash back

### Platform (Android/iOS/macOS/Windows)
iOS

**Comment by aaassseee** [comment]
@zhuwei  Thanks for pointing out the issue, I will check it later.

**Comment by aaassseee** [comment]
@zhuwei  I don't have any problem after import the library. Could you share a full error log? I am guessing you import the library while running your app?

**Comment by zhuwei** [comment]
@aaassseee Sorry, the problem has been resolved.
After I added a new swift file with space in xcode, it will be fine
