### ISSUE TITLE
[feat] Duration of brightness change on Android

### ISSUE THREAD

**Issue by francistac** [aaassseee/screen_brightness#21]
### Description (What is the problem)
There is no way to control how fast the brightness changes on Android.

### Solution suggestion
A 'duration' property that lets you set the duration with the Duration class. Is this possible?

**Comment by aaassseee** [comment]
Hi @francistac. If I am right,  you would like to change the brightness changing animation duration. Right?

**Comment by francistac** [comment]
Correct

**Comment by francistac** [comment]
> Hi @francistac. If I am right, you would like to change the brightness changing animation duration. Right?
Correct

**Comment by aaassseee** [comment]
Hi @francistac, for Android, there isn't any native provided method to change the screen brightness with duration. Any suggestion  and what you are trying to achieve?

**Comment by francistac** [comment]
> Hi @francistac, for Android, there isn't any native provided method to change the screen brightness with duration. Any suggestion and what you are trying to achieve?

I guess there is no possible way to change the duration then, thanks for looking anyways. Thank you for your work so far with this plugin, & thank you for your time.

**Comment by francistac** [comment]
Is there a way to remove the brightness 'fade' animation? Like just an immediate change between different brightness values, with no animation between the transition.

**Comment by aaassseee** [comment]
Nope I don't think so. It depends on the Android ROM.
