### ISSUE TITLE
[bug][Windows] ~ScreenBrightnessWindowsPlugin() could cause Windows crash

### ISSUE THREAD

**Issue by riyulu** [aaassseee/screen_brightness#23]
### Description (bug summary)
crash in windows 
![image](https://github.com/aaassseee/screen_brightness/assets/30603067/f34653cd-2d73-44b8-853b-314966e1ef5f)

Why do you want to delete these two pointers?

![image](https://github.com/aaassseee/screen_brightness/assets/30603067/938236fc-9a0b-4140-8f69-1fba63eff43c)

### Step to reproduce (how to reproduce the bug)
1. git clone https://github.com/aaassseee/screen_brightness.git
2. `cd screen_brightness/screen_brightness/example && flutter run -d windows` and quit
3. open example.sln in visual studio 2022 and run project
4. close windows

### Platform (Android/iOS/macOS/Windows)
windows

**Comment by aaassseee** [comment]
Hi, @riyulu. Thanks for filing this issues. For the delete pointer question, because we need to release the memory when the plugin is getting destruct.

**Comment by wanjm** [comment]
I come across the same problem , which will cause window close very slowly

**Comment by wanjm** [comment]
comments the above two, there are still many other crash.

**Comment by aaassseee** [comment]
Hi @wanjm. Can you provide more info about the crash that you have faced?

**Comment by aaassseee** [comment]
> 

Is that means the window close slowly after you press the close button?

**Comment by riyulu** [comment]
> because we need to release the memory when the plugin is getting destruct.

My idea is that this memory is created externally and does not need to be released internally by the plugin. We should only delete the memory we create ourselves.

**Comment by riyulu** [comment]
And I have found there is a problem here, but I am not sure how to fix it.

**Comment by aaassseee** [comment]
Hi @riyulu. I found this [artical](https://learn.microsoft.com/en-us/cpp/mfc/tn017-destroying-window-objects?view=msvc-170), I am implementing this solution. Hopes it works.

**Comment by aaassseee** [comment]
Hi @riyulu. Is that only deleting window_handler_ causing crashes? Not the registrar_?

**Comment by aaassseee** [comment]
Maybe #15 is also same with this issue.

**Comment by riyulu** [comment]
> Hi @riyulu @wanjm. I have updated screen_brightness_windows to 0.1.2. Please do a pub update to get the latest version to fix the issue.

@aaassseee There are still some issues here. If I have time this weekend, I will raise a PR

**Comment by aaassseee** [comment]
@riyulu thanks for the contribution.

**Comment by aaassseee** [comment]
> I removed all `delete` statements altogether, no crash happens.
> 
> Is it necessary to have those? AFAIK destructor is only being called upon process termination.
> 
> Please proceed with your own intellect, not very sure about this.

Seems other Windows package does not delete pointer when destructor being called

**Comment by alexmercerind** [comment]
Hi!

I appreciate your fixes. It does seem to work in my case.

Thanks!

**Comment by aaassseee** [comment]
Are there any crash after this fix?

**Comment by alexmercerind** [comment]
No. It's all good from what I can tell.
