### ISSUE TITLE
Error: The getter 'isAnimate' isn't defined for the class 'ScreenBrightnessPlatform'.[bug]

### ISSUE THREAD

**Issue by this-sunil** [aaassseee/screen_brightness#30]
### Step to reproduce (how to reproduce the bug)
1. 
Error: The getter 'isAnimate' isn't defined for the class 'ScreenBrightnessPlatform'.

**Comment by aaassseee** [comment]
Hi @this-sunil. Sorry for the inconvenience. May you do a ```flutter pub upgrade```?

**Comment by aaassseee** [comment]
I will update the code with the latest version which is mentioned by @sed1ka https://github.com/aaassseee/screen_brightness/issues/29#issuecomment-2106546939 in next version.

However, would you please now do a ```flutter pub upgrade``` or by adding ```screen_brightness_platform_interface: ^1.0.1``` to pubspec then do a ```flutter pub get``` then remove the ```screen_brightness_platform_interface: ^1.0.1``` from pubspec?

**Comment by aaassseee** [comment]
Hi guys, you can turn off is auto reset on iOS to prevent auto adjust screen brightness for now

**Comment by aaassseee** [comment]
@this-sunil  #30 unsync dependencies issue should be resolved in version 2.0.0+1
