### ISSUE TITLE
[feat] android get the fresh system ScreenBrightness

### ISSUE THREAD

**Issue by yarnping** [aaassseee/screen_brightness#31]
### Description (What is the problem)
IOS keep the systemBrightness fresh, but android not

### Solution suggestion
make them same behavior

**Comment by aaassseee** [comment]
@yarnping thanks for reporting the problem. I am currently working on the system brightness feature which will resolve this problem

**Comment by aaassseee** [comment]
@yarnping this feature should be added in version 2.0.0+1

**Comment by yarnping** [comment]
cool! thank you
