### ISSUE TITLE
[feat] System Brightness listener

### ISSUE THREAD

**Issue by WorkNedoPrograMax** [aaassseee/screen_brightness#32]
### Description (What is the problem)
Would be good to have a possibility to listen to system brightness change

### Solution suggestion
Add a `Stream<double> onSystemBrightnessChanged` like  the way we have it for the current brightness

**Comment by aaassseee** [comment]
Please wait for feature finish

**Comment by aaassseee** [comment]
@WorkNedoPrograMax this feature should be added in version 2.0.0+1
