### ISSUE TITLE
[q] iOS privacy manifest

### ISSUE THREAD

**Issue by Jacqueline94-Koo** [aaassseee/screen_brightness#33]
ITMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: "Frameworks/screen_brightness_ios.framework/screen_brightness_ios_privacy.bundle/PrivacyInfo.xcprivacy". In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

Currently I receive this message when I submit my app to the app store.
How I should update my privacy manifest? I tried few method but incorrect. Could you please give us a guide?

**Comment by aaassseee** [comment]
@Jacqueline94-Koo I face no error during the app submission. Are there any others are facing this issue too?

**Comment by aaassseee** [comment]
Is this just a warning or blocking for your app submission?

**Comment by Jacqueline94-Koo** [comment]
@aaassseee Hi, it will keep pop this warning to me as I submit the app to the app store, but I still can proceed to submit. Just not sure after 24, November 2024, am I still able to submit. 

Or maybe is the version that I'm using got issue? I currently using version ^1.0.0

**Comment by aaassseee** [comment]
Hi @Jacqueline94-Koo you should use version 1.0.1. That version should fix your issue.

**Comment by Jacqueline94-Koo** [comment]
Hi, @aaassseee after I update to v.1.0.1, there is an error for my ios build which same as
[#30](https://github.com/aaassseee/screen_brightness/issues/30) 

So, currently I am using back to version 1.0.0, hopefully this issue can solved soon , thank you

**Comment by aaassseee** [comment]
@Jacqueline94-Koo #30 unsync dependencies issue should be resolved in version 2.0.0+1
