### ISSUE TITLE
[bug] Version 2.0.0 crash in Windows

### ISSUE THREAD

**Issue by chsi020** [aaassseee/screen_brightness#38]
### Description (bug summary)
I am getting **Problem getting monitor brightness** in the debug console with this error dialog. 

![Screenshot 2024-11-08 095932](https://github.com/user-attachments/assets/095487b2-362a-4a90-9179-3a737797d6ae)

### Step to reproduce (how to reproduce the bug)
Run debug with version **2.0.0**, **2.0.0+1** or **2.0.0+2** are showing the same error. It will only work if I change back to **1.0.1**.

### Platform (Android/iOS/macOS/Windows)
Windows

**Comment by aaassseee** [comment]
Hi, @chsi020. Can you show some example code?

**Comment by chsi020** [comment]
Hi @aaassseee,

```
import 'package:screen_brightness/screen_brightness.dart';

@override
  Future<void> registerDependencies({required GetIt getIt}) async {
    final screenBrightnessPlugin = ScreenBrightness();

    getIt
      ..registerLazySingleton<ScreenBrightness>(() => screenBrightnessPlugin);
}
```

```
import 'package:screen_brightness/screen_brightness.dart';

mixin ScreenBrightnessMixin<T extends StatefulWidget> on State<T> {
  double get brightness => 1; // overridable by consumer

  @override
  void initState() {
    super.initState();
    try {
      getIt<ScreenBrightness>().setApplicationScreenBrightness(brightness);
    } catch (e) {
      throw Exception('Failed to get system brightness');
    }
  }

  @override
  void dispose() {
    try {
      getIt<ScreenBrightness>().resetApplicationScreenBrightness();
    } catch (e) {
      throw Exception('Failed to reset system brightness');
    }
    super.dispose();
  }
}
```

**Comment by TheLastFlame** [comment]
> Hi, @chsi020. Can you show some example code?

Just adding the library to pubspec is enough
You don't even need to reference it anywhere.

When running the application, the message “Problem getting monitor brightness” appears in the console

So here's a question
Why is the plugin trying to perform some actions without my knowledge)?

**Comment by aaassseee** [comment]
Hi @TheLastFlame. I reason that the plugin run at start is, the plugin needs to remember the system brightness on the current monitor for use to reset back to. There is no system brightness on windows system, so the plugin needs to remember this initial brightness when launching the application.

**Comment by aaassseee** [comment]
And the crash happened when the app is started or after adjusting the system or the application brightness?

**Comment by chsi020** [comment]
Hi @aaassseee, 
I ran the sample code, and it started up fine. I am using an HP ZBook notebook along with an old Dell monitor. The crash occurred when the app started. The only way to make it work was to revert the pub version back to 1.0.1.

Best regards,
James

**Comment by aaassseee** [comment]
@chsi020 Is that means the sample code works fine without any crash?

**Comment by chsi020** [comment]
> @chsi020 Is that means the sample code works fine without any crash?

Hi @aaassseee,
The sample code works fine without crash.

**Comment by vincent-hoodoo** [comment]
We are also running into the same issue. Our app crashes on startup, and the only error message logged is also `Problem getting monitor brightness`.

However, we are able to run the example app correctly...

**Comment by aaassseee** [comment]
Hi @chsi020 , @vincent-hoodoo . Can you gays provide a minimum runnable example for me to test? It is hard to reproduce.

**Comment by TheLastFlame** [comment]
> Hi @chsi020 , @vincent-hoodoo . Can you gays provide a minimum runnable example for me to test? It is hard to reproduce.

It is enough to create a new project with Empty application template and execute flutter pub add screen_brightness in the terminal
This is the most minimal example.

This error probably cannot be reproduced on your device.

![image](https://github.com/user-attachments/assets/4fbd07aa-23b8-496d-8bf8-e092f3391baa)

**Comment by aaassseee** [comment]
Hi @TheLastFlame thanks for the screen capture. May I ask is that downgrade to 1.0.1 will not crash?

**Comment by TheLastFlame** [comment]
> Hi @TheLastFlame thanks for the screen capture. May I ask is that downgrade to 1.0.1 will not crash?

Right, after downgrading to 1.0.1 the problem disappears

**Comment by aaassseee** [comment]
Thanks for the help, I will take a look.

**Comment by Predidit** [comment]
@aaassseee 

I also encountered this annoying issue, and it seems I found the trigger condition for this problem. The above error is thrown when this package runs together with the most popular Flutter audio and video component, media_kit. I looked into the internals of media_kit, and it also references screenbrightness_android and screenbrightness_platform_interface internally to implement the brightness adjustment function of its built-in player control panel. I think this might be causing the issue, but I am not sure where exactly the problem is coming from.

**Comment by aaassseee** [comment]
Hi @ALL, are you guys are all using windows notebook?

**Comment by Predidit** [comment]
@aaassseee Yeah, I working on laptop.

**Comment by aaassseee** [comment]
Hi @Predidit, can you help me to comment lines of code in https://github.com/aaassseee/screen_brightness/blob/175b30d7df16ece10420e2c643f6f56e7f5431b4/screen_brightness_windows/windows/src/screen_brightness_windows_plugin.cpp#L24-L31 to test is the plugin can run without crash?

**Comment by Predidit** [comment]
@aaassseee 

Sorry, but I don't know how to fix the problem here. If you want to make any changes, I would be happy to test them for you.

It seems to be an issue from the CMake build system because it can be triggered simply by referencing both the screen_brightness and media_kit packages in pubspec.yaml and initializing the media_kit package. The screen_brightness package doesn't even need to be imported in any part of the Dart code. It is possible that the CMake file of media_kit modifies some CMake variables globally. I don't know why screen_brightness 1.0.1 doesn't trigger this issue.

**Comment by aaassseee** [comment]
@Predidit But @chsi020 @TheLastFlame @vincent-hoodoo said that

> > Hi @chsi020 , @vincent-hoodoo . Can you gays provide a minimum runnable example for me to test? It is hard to reproduce.
> 
> It is enough to create a new project with Empty application template and execute flutter pub add screen_brightness in the terminal This is the most minimal example.
> 
> This error probably cannot be reproduced on your device.
> 
> ![image](https://private-user-images.githubusercontent.com/131446187/388585604-4fbd07aa-23b8-496d-8bf8-e092f3391baa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MzY1NDksIm5iZiI6MTczMzYzNjI0OSwicGF0aCI6Ii8xMzE0NDYxODcvMzg4NTg1NjA0LTRmYmQwN2FhLTIzYjgtNDk2ZC04YmY4LWUwOTJmMzM5MWJhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQwNTM3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTIzNTRlZTgzYzQyY2M1MjMwZDYxNDljZDg3ODFhNDBmYTI1ZmM1YzA2YTQzMDk1MTY4NTIzYjIxZDgyMGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.20JH4xe6XjVaw710LZp70G4VYPN4h1BJusufrZQUcy0)

using the minimal project would also produce this crash.

Would you help to fact check this plugin itself causing the crash?

**Comment by aaassseee** [comment]
And are you using the media_kit with screen_brightness at the same time will cause this crash? If so, I can give it a try.

**Comment by Predidit** [comment]
Okay, I will create a completely blank project for testing. I would like to add that the try-catch block above worked. When the media-kit package is not present, the console outputs a brightness fetch error message that does not prevent the program from continuing to run.

**Comment by aaassseee** [comment]
Okey! That must be one of the clued.  Thanks for the help though @Predidit.

**Comment by Predidit** [comment]
@aaassseee 

Sorry, after testing with a blank project, I think I made a serious mistake. The crash occurs with just flutter pub add screen_brightness, without needing any other packages. The complex dependencies in my actual project interfered with the initial test.

**Comment by aaassseee** [comment]
@Predidit Not a problem though,. Can you help me to remove the lines from local pub cache
https://github.com/aaassseee/screen_brightness/blob/175b30d7df16ece10420e2c643f6f56e7f5431b4/screen_brightness_windows/windows/src/screen_brightness_windows_plugin.cpp#L24-L31

To test if getting the initial brightness causing the crash?

**Comment by Predidit** [comment]
@aaassseee still crash
![screenshoot_20241208144345](https://github.com/user-attachments/assets/71ae8299-5396-4a45-96aa-e677bb4a634d)

**Comment by aaassseee** [comment]
@Predidit that's weird. Can you undo the changes than comment this part?
https://github.com/aaassseee/screen_brightness/blob/175b30d7df16ece10420e2c643f6f56e7f5431b4/screen_brightness_windows/windows/src/screen_brightness_windows_plugin.cpp#L61C1-L72C143

**Comment by Predidit** [comment]
@aaassseee still crash

I removed the code on line 72 to pass the compilation.

![screenshoot_20241208145435](https://github.com/user-attachments/assets/cd205db0-2a56-4552-9347-fa487468539b)

**Comment by aaassseee** [comment]
if comment the whole section from
https://github.com/aaassseee/screen_brightness/blob/175b30d7df16ece10420e2c643f6f56e7f5431b4/screen_brightness_windows/windows/src/screen_brightness_windows_plugin.cpp#L61-L85

**Comment by aaassseee** [comment]
If still crash, can you undo the changes and comment this part?
https://github.com/aaassseee/screen_brightness/blob/175b30d7df16ece10420e2c643f6f56e7f5431b4/screen_brightness_windows/windows/src/screen_brightness_windows_plugin.cpp#L346-L409

**Comment by Predidit** [comment]
@aaassseee good news

I removed L346-L408 (all the HandleWindowProc function)

It doesn't crash now.

But it still crash when I only remove L348-L377.

We are getting close. I am trying to find the breakpoint.

**Comment by aaassseee** [comment]
@Predidit Thanks for the help bro.
I think I know where is the problem.

**Comment by aaassseee** [comment]
@Predidit It seems missing the try catch on HandleWindowProc method

**Comment by aaassseee** [comment]
@Predidit just the last test. Can you able to run the program with replacing the HandleWindowProc function with this fix?
```cpp
	std::optional<LRESULT> ScreenBrightnessWindowsPlugin::HandleWindowProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
	{
		try {
			switch (message)
			{
			case WM_SIZE:
				switch (wParam)
				{
				case SIZE_MINIMIZED:
					if (!is_auto_reset_)
					{
						return std::nullopt;
					}

					OnApplicationPause();
					break;

				case SIZE_MAXIMIZED:
				case SIZE_RESTORED:
					if (!is_auto_reset_)
					{
						return std::nullopt;
					}

					GetScreenBrightness(minimum_screen_brightness_, system_screen_brightness_, maximum_screen_brightness_);
					HandleSystemScreenBrightnessChanged(system_screen_brightness_);
					if (application_screen_brightness_ == -1)
					{
						HandleApplicationScreenBrightnessChanged(system_screen_brightness_);
					}

					OnApplicationResume();
					break;
				}
				break;

			case WM_DESTROY:
			case WM_CLOSE:
				OnApplicationPause();
				break;

			case WM_ACTIVATEAPP:
				if (!is_auto_reset_)
				{
					return std::nullopt;
				}

				bool is_activate = bool(wParam);
				if (is_activate)
				{
					GetScreenBrightness(minimum_screen_brightness_, system_screen_brightness_, maximum_screen_brightness_);
					HandleSystemScreenBrightnessChanged(system_screen_brightness_);
					if (application_screen_brightness_ == -1)
					{
						HandleApplicationScreenBrightnessChanged(system_screen_brightness_);
					}

					OnApplicationResume();
					break;
				}
				else
				{
					OnApplicationPause();
				}
				break;
			}
		}
		catch (const std::exception& exception)
		{
			std::cout << exception.what() << std::endl;
		}

		// allow another plugin to process message
		return std::nullopt;
	}
```

**Comment by Predidit** [comment]
@aaassseee 

It works very well

**Comment by aaassseee** [comment]
@Predidit @chsi020 @vincent-hoodoo @TheLastFlame Thanks for you guys help.

**Comment by aaassseee** [comment]
Issue has been solved in version 2.0.1, please download and test again.

**Comment by chsi020** [comment]
Thank you @aaassseee 

I just tested version 2.0.1, and the app no longer crashes. Thank you so much for sorting this out for us. Much appreciated.

**Comment by vincent-hoodoo** [comment]
All good on our side too, thank you for taking the time to fix it.

**Comment by aaassseee** [comment]
@chsi020  @vincent-hoodoo You are welcome.
