### ISSUE TITLE
brightness randomly drop down to zero when user lock screen

### ISSUE THREAD

**Issue by aaassseee** [aaassseee/screen_brightness#5]
### Description (bug summary)
Screen brightness will drop to zero randomly

### Step to reproduce (how to reproduce the bug)
1. go to controller page in example
2. lock screen
3. wait for 3 - 5 min
4. unlock screen
5. reopen the app

### Platform
iOS

**Comment by 31Carlton7** [comment]
It also resets back to what it originally was after using the `setBrightness()` method and then going to Control Center on iOS.

**Comment by aaassseee** [comment]
If you are talking about the auto reset when user is not reading the app screen. That is not a bug, that is a feature.
The plugin has to reset the brightness due to the iOS system didn't have function to reset it.
I am having plans on supporting no auto set and reset brightness in the future however not now. What is your concerns or use case on the brightness reset to system brightness when user is not reading or using the app?

**Comment by aaassseee** [comment]
Issue has been identified. Due to the iOS system will stop activity when application has been too long in background.
The notification on brightness change which created in applicationWillResignActive will no longer notify the plugin to preform changes.
https://github.com/aaassseee/screen_brightness/blob/b0dd4d4d298eb907627ee6b85e46336d99232c14/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift#L127-L130
That means when iPhone auto screen lock after time, brightness notification will notify the plugin to change system brightness drop to zero.  Then onApplicationPause() has been double call after in both applicationWillResignActive and applicationDidEnterBackground. So the brightness will be falsely set to zero.
https://github.com/aaassseee/screen_brightness/blob/b0dd4d4d298eb907627ee6b85e46336d99232c14/screen_brightness_ios/ios/Classes/SwiftScreenBrightnessIosPlugin.swift#L137-L139

**Comment by 31Carlton7** [comment]
Thanks. At first I did not exactly understand the point, but after the clarification it does make a lot more sense. Will a control be introduced to optionally have it on or off?

**Comment by aaassseee** [comment]
It will be happening within this month.
