### ISSUE TITLE
[feature required] support fade animation

### ISSUE THREAD

**Issue by ash0080** [aaassseee/screen_brightness#7]
Reference [here](https://stackoverflow.com/questions/15840979/how-to-set-screen-brightness-with-fade-animations#:~:text=11-,Swift%205,-import%20UIKit%0A%0Aextension)

**Comment by aaassseee** [comment]
@ash0080 Because I don't have an iPhone nearby. Could you help me for testing the feature?

**Comment by ash0080** [comment]
> @ash0080 Because I don't have an iPhone nearby. Could you help me for testing the feature?

OK

**Comment by ash0080** [comment]
Not work for both emulator and real device
``` 
failure in assertBarrierOnQueue of <FBSSerialQueue:0x282db5740> (FBSSerialQueue.m:121) : threading violation: expected the main thread
* thread #3, queue = 'NSOperationQueue 0x103912cd0 (QOS: UNSPECIFIED)', stop reason = EXC_BREAKPOINT (code=1, subcode=0x192718684)
    frame #0: 0x0000000192718684 FrontBoardServices`-[FBSSerialQueue assertBarrierOnQueue] + 448
FrontBoardServices`-[FBSSerialQueue assertBarrierOnQueue]:
->  0x192718684 <+448>: brk    #0
    0x192718688 <+452>: brk    #0x1
    0x19271868c <+456>: bl     0x18b9e7c5c               ; __stack_chk_fail
FrontBoardServices`-[FBSMutableSceneSettings mutableCopyWithZone:]:
    0x192718690 <+0>:   pacibsp 
Target 0: (Runner) stopped.
```

**Comment by aaassseee** [comment]
Could you give it another try?

**Comment by ash0080** [comment]
> Could you give it another try?

maybe works not very sure, I may need to write an example myself to confirm, because example is a slider, confirmed that ,  reset has no fade effects

**Comment by aaassseee** [comment]
I think I found the issue with animating brightness value, and it will cause reset not having effect.
Thanks for the help. You may try again.

**Comment by aaassseee** [comment]
You can also test the scenario with route aware example. That should be the correct test case.

**Comment by aaassseee** [comment]
@ash0080 I have completed this feature and tested in real device today. Would you like to give it a try and see is this what you want? Remember this feature only available in [screen_brightness_ios example](https://github.com/aaassseee/screen_brightness/tree/develop/screen_brightness_ios/example). If you want to test it on screen_brightness use screen_brightness_ios in local by uncomment these [lines](https://github.com/aaassseee/screen_brightness/blob/d88e3e85acf7b2a23ed9cbd8879ab34b03920308/screen_brightness/pubspec.yaml#L19-L20) and comment this [line](https://github.com/aaassseee/screen_brightness/blob/d88e3e85acf7b2a23ed9cbd8879ab34b03920308/screen_brightness/pubspec.yaml#L23).

**Comment by aaassseee** [comment]
@ash0080 I have changed the relationship between fps and step. Would you try again? I think it improve a lot with my device.

**Comment by ash0080** [comment]
> @ash0080 I have changed the relationship between fps and step. Would you try again? I think it improve a lot with my device.

I've tested it, it's great, thanks a lot! 👍
