### ISSUE TITLE
System brigthness slider is disabled because controlled by the running app 

### ISSUE THREAD

**Issue by Ciock** [aaassseee/screen_brightness#8]
### Description
I got this message if I try to adjust the brightness manually from the system slider:

> Can't adjust brihtness in the quick panel right now because it's being controlled by the currently running app.

![Screenshot_20220325-115449](https://user-images.githubusercontent.com/35781302/160108721-48c6da6c-d9dc-4c02-a863-85ed9ef589aa.jpg)

I use this plugin to set the brighness at a low value when entering my sleep mode screen. This is the code:
```dart
import 'package:async/async.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:screen_brightness/screen_brightness.dart';

import '../screens/sleep_mode/sleep_mode.screen.dart';

const _sleepModeInactivityTimeout = Duration(seconds: 5);
const _sleepModeTransitionDuration = Duration(seconds: 1);
const _lowScreenBrightnessValue = 0.2;

class SleepModeListener extends StatefulWidget {
  const SleepModeListener({Key? key, required this.child}) : super(key: key);

  final Widget child;

  @override
  State<SleepModeListener> createState() => _SleepModeListenerState();
}

class _SleepModeListenerState extends State<SleepModeListener> {
  late RestartableTimer _sleepTimer;

  @override
  void initState() {
    super.initState();
    _sleepTimer =
        RestartableTimer(_sleepModeInactivityTimeout, _setToSleepMode);
  }

  @override
  Widget build(BuildContext context) => Listener(
        onPointerDown: (event) {
          _sleepTimer.reset();
        },
        child: widget.child,
      );

  void _setToSleepMode() async {
    _sleepTimer.cancel();

    await _setScreenBrightnessDown();

    Get.dialog(
      const SleepMode(),
      transitionDuration: _sleepModeTransitionDuration,
      useSafeArea: false,
    ).then(
      (value) {
        _resetScreenBrightness();
        _sleepTimer.reset();
      },
    );
  }

  Future<void> _setScreenBrightnessDown() async {
    ScreenBrightness().setScreenBrightness(_lowScreenBrightnessValue);
  }

  Future<void> _resetScreenBrightness() =>
      ScreenBrightness().resetScreenBrightness();
}
```

### Step to reproduce
1. just call `ScreenBrightness().setScreenBrightness()`
2. Then try to move the system slider

### Platform
Found on an Android physical device with Android 11, emulator works fine.

**Comment by aaassseee** [comment]
Hi @Ciock, that's how Android OS works. May be you didn't know there are difference between application brightness and system brightness. 

Changing application brightness means only affect when the application but not the system brightness. 

Application brightness will auto reset when user exit or pause the application. Moreover, system brightness will be unchangeable after setting application brightness on higher Android SDK.

This plugin only changing the application brightness but not system brightness. If you want to change Android system brightness, permission must be required. In addition,, iOS didn't provide any solution on changing system brightness.

Hopes theses information can help you.

**Comment by aaassseee** [comment]
Also you can exit or pause the application if you want to change system brightness

**Comment by Ciock** [comment]
Thank you for the explanation. Maybe it would be useful to write this down in the readme to be crystal clear on what this plugin does.
The fact that it doesn't need permissions is important and it must be in the front page 😁.
