### ISSUE TITLE
How to Set Platform Brightness in android When Click one Page Screen will be brightness and again i go back the screen will reduce and go back to platform brightness?

### ISSUE THREAD

**Issue by DazzlingCVa** [aaassseee/screen_brightness#9]
### Step to reproduce (how to reproduce the bug)
1. how to set Platform Brightness in this package

### Platform (Android/iOS/macOS/Windows)
Android,Ios

**Comment by aaassseee** [comment]
Hi, @DazzlingCVa. Please take a look at the example Route aware example page. I think that is what you needed.
